image: node

variables:
  PRERENDER: 'disabled'
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install --pure-lockfile --ignore-engines

job:
  script:
  - yarn run build --no-progress
