#id: masterarbeit
tags:
  - python
  - latex
  - astronomy
  - major
url: https://lw1.at/s/astro/MastersThesis.pdf
date: 2022-03-31
github: Findus23/rebound-collisions
subtitle:
  Estimating Water Transfer during Planetary Formation using Interpolated Results from SPH Collision Catalogues
de:
  title: Masterarbeit
en:
  title: Master's thesis
