id: mercury
tags:
- astronomy
github: Findus23/mercury
date: 2013-11-07
url: https://github.com/Findus23/Mercury/raw/master/ausarbeitung/Prasentation.pdf
en:
  title: "Mercury: Planetary Simulation"
de:
  title: "Mercury: Planentensimulation"
