id: maskDetector
title: Mask Detector
tags:
- javascript
- browserExtension
date: 2017-09-20
url: https://chrome.google.com/webstore/detail/mask-detector/kkbhnlbbfpkdbipkjgagfagcbaacmfge
tryout: true
github: Findus23/mask-detector
license:
  id: GPL3
  url: https://github.com/Findus23/mask-detector/blob/master/LICENSE
