id: classiccounter
title: Matomo Classic Counter
tags:
  - php
  - matomo
date: 2019-03-10
github: Findus23/plugin-ClassicCounter
url: https://plugins.matomo.org/ClassicCounter
license:
  id: GPL3
  url: https://github.com/Findus23/plugin-ClassicCounter/blob/master/LICENSE
single_language: en
