id: bachelorarbeit
tags:
  - python
  - latex
  - astronomy
  - major
url: https://lw1.at/r/bachelorarbeit-pdf
date: 2019-08-30
github: Findus23/collision-analysis-and-interpolation
iframe:
  url: https://video.lw1.at/videos/embed/15108d24-2e82-473c-8a20-8e8e08de788e?loop=1
  allowfullscreen: True
  sandbox: allow-same-origin allow-scripts
  color: black
subtitle:
  Interpolated water retention after two-body collisions using Neural Networks and linear interpolation methods


de:
  title: Bachelorarbeit
en:
  title: Bachelor's thesis
